### ISSUE TITLE
Calls Screener

### ISSUE THREAD

**Issue by sam-cap** [bigsaso/StockOptions#5]
User Action: Select a ticker he wants to check by inputting it in a text field in the website.

Screener Actions: For all expiration dates available for that stock:
1. Pick the best 10 strike prices based on highest OI and volume.
2. At these strike prices+exp dates, calculate the option price % change when the stock moves 1% after accounting for fees, where:
     - Fees = 22$/Contract Price
     - Option price % change = C(days till exp - 1)/last price - fees
3. Display data showing Top 10 picks and remaining picks in two separate tables.

Formula to calculate C(t) = S*N(d1) - K*e^(-rt)*N(d2), where:
    - S = stock price
    - t = time until expiry (in years)
    - K = strike price
    - r = risk free rate (for the year)
    - N(d1) = Calculate d1 (the z value to use in the z table to find N(d1)), where d1 = (ln(S/K) + (r + IV^2/2)*t)/IV*sqrt(t)
    - N(d2) = Calculate d2 (the z value to use in the z table to find N(d2)), where d2 = d1 - IV*sqrt(t)

**Comment by bigsaso** [comment]
Created functions. Next: Create page to display data for a selected expiration date

**Comment by bigsaso** [comment]
done in ef35a453175858d13e8037b4fc4d8a40e282aca0
